import React, { useContext } from 'react';
import { Context } from '../../main';

function About() {
  const {mode} = useContext(Context)
  return (
    <article className={mode === "dark" ? "dark-bg about" : "light-bg abou"}>
      <div className="container">
      <h2>About</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error nulla odit magnam velit! Asperiores doloribus molestiae libero magnam ipsum! Non, totam atque? Accusamus aliquid, aspernatur quam repudiandae optio, deserunt pariatur possimus minus voluptatibus, ad explicabo enim quidem modi perspiciatis a? Ea, corrupti suscipit sed et labore tempora aspernatur hic aperiam? Porro aliquam alias vero placeat illo vel totam possimus delectus quibusdam atque. Tempore ipsa pariatur ex sequi labore tenetur, maiores magnam accusantium. Qui expedita minus debitis quas sint, exercitationem est cum corrupti sunt quae. Vero ab ratione debitis repellendus adipisci tempore id nulla dolorem voluptates et nihil, odio deleniti esse totam laudantium earum deserunt ducimus. Neque maxime praesentium accusamus odio dolores, quod, dicta, nemo harum unde quam ipsum eos! Veritatis earum recusandae architecto. Perferendis repellat omnis a voluptas aliquid harum ratione accusantium, reiciendis facilis voluptatum, numquam odit iusto culpa nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error nulla odit magnam velit! Asperiores doloribus molestiae libero magnam ipsum! Non, totam atque? Accusamus aliquid, aspernatur quam repudiandae optio, deserunt pariatur possimus minus voluptatibus, ad explicabo enim quidem modi perspiciatis a? Ea, corrupti suscipit sed et labore tempora aspernatur hic aperiam? Porro aliquam alias vero placeat illo vel totam possimus delectus quibusdam atque. Tempore ipsa pariatur ex sequi labore tenetur, maiores magnam accusantium. Qui expedita minus debitis quas sint, exercitationem est cum corrupti sunt quae. Vero ab ratione debitis repellendus adipisci tempore id nulla dolorem voluptates et nihil, odio deleniti esse totam laudantium earum deserunt ducimus. Neque maxime praesentium accusamus odio dolores, quod, dicta, nemo harum unde quam ipsum eos! Veritatis earum recusandae architecto. Perferendis repellat omnis a voluptas aliquid harum ratione accusantium, reiciendis facilis voluptatum, numquam odit iusto culpa nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error nulla odit magnam velit! Asperiores doloribus molestiae libero magnam ipsum! Non, totam atque? Accusamus aliquid, aspernatur quam repudiandae optio, deserunt pariatur possimus minus voluptatibus, ad explicabo enim quidem modi perspiciatis a? Ea, corrupti suscipit sed et labore tempora aspernatur hic aperiam? Porro aliquam alias vero placeat illo vel totam possimus delectus quibusdam atque. Tempore ipsa pariatur ex sequi labore tenetur, maiores magnam accusantium. Qui expedita minus debitis quas sint, exercitationem est cum corrupti sunt quae. Vero ab ratione debitis repellendus adipisci tempore id nulla dolorem voluptates et nihil, odio deleniti esse totam laudantium earum deserunt ducimus. Neque maxime praesentium accusamus odio dolores, quod, dicta, nemo harum unde quam ipsum eos! Veritatis earum recusandae architecto. Perferendis repellat omnis a voluptas aliquid harum ratione accusantium, reiciendis facilis voluptatum, numquam odit iusto culpa nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error nulla odit magnam velit! Asperiores doloribus molestiae libero magnam ipsum! Non, totam atque? Accusamus aliquid, aspernatur quam repudiandae optio, deserunt pariatur possimus minus voluptatibus, ad explicabo enim quidem modi perspiciatis a? Ea, corrupti suscipit sed et labore tempora aspernatur hic aperiam? Porro aliquam alias vero placeat illo vel totam possimus delectus quibusdam atque. Tempore ipsa pariatur ex sequi labore tenetur, maiores magnam accusantium. Qui expedita minus debitis quas sint, exercitationem est cum corrupti sunt quae. Vero ab ratione debitis repellendus adipisci tempore id nulla dolorem voluptates et nihil, odio deleniti esse totam laudantium earum deserunt ducimus. Neque maxime praesentium accusamus odio dolores, quod, dicta, nemo harum unde quam ipsum eos! Veritatis earum recusandae architecto. Perferendis repellat omnis a voluptas aliquid harum ratione accusantium, reiciendis facilis voluptatum, numquam odit iusto culpa nostrum.</p>
      </div>
    </article>
  );
}

export default About;
